### ISSUE TITLE
Navbar overflowing

### ISSUE THREAD

**Issue by aravindvnair99** [Diversity-In-DSC/dsc-webathon#32]
![image](https://user-images.githubusercontent.com/22199259/98642260-2716de80-2353-11eb-88f5-c58c5f150b25.png)

**Comment by GearGit** [comment]
As much as I remember, this issue was resolved. Please check and let me know

**Comment by aravindvnair99** [comment]
> As much as I remember, this issue was resolved. Please check and let me know

@GearGit the issue persists. My display resolution is 1366*768.

**Comment by aravindvnair99** [comment]
@GearGit Refer this: https://github.com/Diversity-In-DSC/dsc-webathon/pull/40#issuecomment-725218486

**Comment by aravindvnair99** [comment]
New repository: https://github.com/Diversity-In-DSC/DSC-WoW-Front-end
